# Dockerfile for the service container
FROM node:22-alpine AS user

WORKDIR /usr/src/user

# Copy application-specific files
COPY service/package.json ./
RUN npm install --production
COPY ../shared ./shared
COPY service/ ./service

# Mount shared volumes from the base container (node_modules and shared code)
VOLUME /usr/src/user/shared
VOLUME /usr/src/user/node_modules
VOLUME /usr/src/user/.env

CMD ["node", "service/server.js"]
