FROM node:22-alpine AS common-base

WORKDIR /usr/src/base

# Copy package.json and install dependencies
COPY /base/package.json ./
RUN npm install
RUN apk add --no-cache coreutils
COPY .env .env 
# Copy shared code into container
COPY ../shared ./shared


# Copy environment variables into container

# Expose shared code and node_modules as volumes for reuse
VOLUME /usr/src/common-base/shared
VOLUME /usr/src/common-base/node_modules

CMD tail -f /dev/null
